### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/asbuild#19]
Currently looking into this in other repositories, but since it may affect local forks and I do not have one of `asbuild`, I figured I let you folks know instead :)

**Comment by willemneal** [comment]
It seems I don't have the permission to access the settings.

**Comment by dcodeIO** [comment]
Hmm, but if I rename now that will work for you? :)

**Comment by dcodeIO** [comment]
The default branch has been renamed!

*master* is now named *main*

If you have a local clone, you can update it by running:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by willemneal** [comment]
Sweet thanks!
