### ISSUE TITLE
[Usability] [Branding] Change name to "assemblyscript-build"

### ISSUE THREAD

**Issue by chadoh** [AssemblyScript/asbuild#8]
Our newbie [NEAR](https://near.org) developers love AssemblyScript, but right now there's some friction when curious newbies want to dig in and figure out how their new app created with `create-near-app` works.

* The script name, `asb`, doesn't give much info. If users don't know to look in `./node_modules/.bin` for symlinks, they have little way to figure out that this is "AS Build", and that it comes from the `asbuild` package on NPM.
* Making a script name match the current package name, `asbuild`, is an improvement, but still has some problems. It still might not be super obvious that to users who are both unfamiliar with NEAR and with AssemblyScript that this builds _assemblyscript_, since they are learning about both projects at once. They might not yet even know about AssemblyScript, let alone that it sometimes gets abbreviated as "as". "As" is a common English word.

If the main package name were "assemblyscript-build" and I could use longwinded command like `assemblyscript-build --target debug`, this would be great branding. Newbies coming to AssemblyScript through a backdoor like NEAR would immediately start to understand that this is an AssemblyScript thing, not a NEAR thing, and they'd be able to Google "assemblyscript-build" to find the package on NPM. From there, they could learn more about AssemblyScript, as well as the Pro Tip that they can use the alias `asb` instead of the longwinded, self-documenting version.

**Comment by willemneal** [comment]
We now have three two more aliases for the binary: `asbuild` and `assemblyscript-build`
